// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5hHDwu9o46O42C_k8ZnnT50gW7ygmFs4',
    authDomain: 'peacefulworkouts.firebaseapp.com',
    projectId: 'peacefulworkouts',
    storageBucket: 'peacefulworkouts.appspot.com',
    messagingSenderId: '1008908513514',
    appId: '1:1008908513514:web:f2b4969b4c7a691a3f2793',
    measurementId: 'G-JREFGTKYH4',
  );

  // Add these configurations when you need Android/iOS support
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // Get from Firebase Console
    appId: 'YOUR_ANDROID_APP_ID', // Get from Firebase Console
    messagingSenderId: '1008908513514',
    projectId: 'peacefulworkouts',
    storageBucket: 'peacefulworkouts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Get from Firebase Console
    appId: 'YOUR_IOS_APP_ID', // Get from Firebase Console
    messagingSenderId: '1008908513514',
    projectId: 'peacefulworkouts',
    storageBucket: 'peacefulworkouts.appspot.com',
    iosBundleId: 'com.example.peacefulworkouts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Get from Firebase Console
    appId: 'YOUR_MACOS_APP_ID', // Get from Firebase Console
    messagingSenderId: '1008908513514',
    projectId: 'peacefulworkouts',
    storageBucket: 'peacefulworkouts.appspot.com',
    iosBundleId: 'com.example.peacefulworkouts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5hHDwu9o46O42C_k8ZnnT50gW7ygmFs4',
    authDomain: 'peacefulworkouts.firebaseapp.com',
    projectId: 'peacefulworkouts',
    storageBucket: 'peacefulworkouts.appspot.com',
    messagingSenderId: '1008908513514',
    appId: '1:1008908513514:web:f2b4969b4c7a691a3f2793',
    measurementId: 'G-JREFGTKYH4',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC5hHDwu9o46O42C_k8ZnnT50gW7ygmFs4',
    authDomain: 'peacefulworkouts.firebaseapp.com',
    projectId: 'peacefulworkouts',
    storageBucket: 'peacefulworkouts.appspot.com',
    messagingSenderId: '1008908513514',
    appId: '1:1008908513514:web:f2b4969b4c7a691a3f2793',
    measurementId: 'G-JREFGTKYH4',
  );
}